env_type: habitat
task_suite_name: vln_r2r

seed: 0
group_size: 1
reward_coef: 5.0
total_num_envs: null
auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 512
max_episode_steps: 512
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: False

init_params:
  config_path: "rlinf/envs/habitat/configs/vlnce_r2r.yaml"