simulator_type: robocasa

# Robot configuration
robot_name: PandaOmron

# Camera configuration
# Pi0 model uses two 128x128 cameras: left view and wrist view
camera_names:
  - robot0_agentview_left
  - robot0_eye_in_hand

# Task configuration (simplified atomic tasks)
task_names:
  # - OpenSingleDoor
  # - TurnOnSinkFaucet
  - CloseDrawer

auto_reset: True
ignore_terminations: True
max_episode_steps: ${algorithm.max_episode_steps}

use_rel_reward: True
reward_coef: ${algorithm.reward_coef}
only_eval: True

seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True

num_envs: 9

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  camera_heights: 224
  camera_widths: 224
